### ISSUE TITLE
Add "RUN_DEFAULT_MIGRATION" environment variable in Dockerfile

### ISSUE THREAD

**Issue by mnlbox** [platyplus/authentication-server#2]
@plmercereau I'm try to some modification and add this to my docker-compose file like below:
```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - ./pgadmin_files:/var/lib/pgadmin
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha38
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an access key
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key":"<public key>"}'
  authentication:
    build:
      context: ../../authenticationServer/
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - "postgres"
    ports:
    - "6060:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      AUTH_PRIVATE_KEY: "<private key>"
      AUTH_PUBLIC_KEY: "<public key>"
```
but it seems that knex not running migration to create tables.
I think it's better to have a environment variable for example called `RUN_DEFAULT_MIGRATION` and if we set it to true we run migration in Dockerfile.
